version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: case-streaks-app
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=YoJQvKdD+UtJkmK/JUhNbEDBrw30upbT0Utxhnl8LQs=
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - case-streaks-network
    command: npm run dev

networks:
  case-streaks-network:
    driver: bridge
